In [1]:
import numpy as np

In [2]:
import sys
import os

sys.path.append(os.path.abspath('../'))

del sys, os

In [3]:
import matplotlib.pyplot as plt

In [4]:
# LaTeX rendering in graphs
try:
    plt.rc('text', usetex=True)
except:
    pass

plt.rc('font', family='serif')

# High resolution graphs
%config InlineBackend.figure_format = 'retina'

In [5]:
import torch

In [6]:
%reload_ext autoreload
%autoreload 2

In [7]:
import models.rnn as networks

# Model

## RNN

In [8]:
rnn = networks.RNN()

In [9]:
x = torch.randn((2, 5))

In [10]:
torch.cat(tuple([i * torch.ones((1, 5)) for i in range(1)]))

tensor([[0., 0., 0., 0., 0.]])

In [11]:
rnn.reset()

In [56]:
rnn.predict(x)

tensor([[ 0.0950,  0.1943,  0.1734, -0.3262],
        [ 0.0704,  0.1886,  0.2076, -0.2887]])

In [54]:
rnn(x)

tensor([[ 0.0781,  0.2130,  0.2169, -0.2720],
        [ 0.0818,  0.2089,  0.2073, -0.2839]], grad_fn=<AddmmBackward>)

## Attentive RNN

In [23]:
arnn = networks.AttentiveRNN(horizon=6)

In [24]:
x = torch.randn((2, 5))

In [39]:
arnn.reset()

In [75]:
print(len(arnn.context))
arnn.predict(x)

0


tensor([[-0.3430, -0.0410, -0.2369,  0.1109],
        [-0.4024, -0.0563, -0.2040,  0.1514]])