In [1]:
import numpy as np

In [2]:
import sys
import os

sys.path.append(os.path.abspath('../'))

del sys, os

In [3]:
import matplotlib.pyplot as plt

In [4]:
# LaTeX rendering in graphs
try:
    plt.rc('text', usetex=True)
except:
    pass

plt.rc('font', family='serif')

# High resolution graphs
%config InlineBackend.figure_format = 'retina'

In [5]:
import torch

In [6]:
%reload_ext autoreload
%autoreload 2

In [12]:
import models.rnn as networks

# Model

## RNN

In [34]:
rnn = networks.RNN()

In [39]:
x = torch.randn((2, 5))

In [40]:
torch.cat(tuple([i * torch.ones((1, 5)) for i in range(1)]))

tensor([[0., 0., 0., 0., 0.]])

In [41]:
rnn.reset()

In [54]:
rnn(x)

tensor([[ 0.4638,  0.2134,  0.2997, -0.2252],
        [ 0.4653,  0.2158,  0.3119, -0.2496]], grad_fn=<AddmmBackward>)

In [57]:
print(len(rnn.context))
rnn(x)

2


tensor([[ 0.4628,  0.2131,  0.2995, -0.2250],
        [ 0.4319,  0.1516,  0.2793, -0.1201]], grad_fn=<AddmmBackward>)

## Attentive RNN

In [212]:
arnn = models.rnn.AttentiveRNN(horizon=0)

In [213]:
x = torch.randn((2, 5))

In [214]:
arnn.reset()

In [248]:
print(len(arnn.context))
arnn(x)

1


tensor([[-0.3560, -0.0505,  0.0288, -0.3792],
        [-0.3909, -0.0565,  0.0178, -0.3644]], grad_fn=<AddmmBackward>)