In [2]:
import numpy as np

In [3]:
import sys
import os

sys.path.append(os.path.abspath('../'))

del sys, os

In [4]:
import matplotlib.pyplot as plt

In [5]:
# LaTeX rendering in graphs
try:
    plt.rc('text', usetex=True)
except:
    pass

plt.rc('font', family='serif')

# High resolution graphs
%config InlineBackend.figure_format = 'retina'

In [6]:
import torch

In [7]:
%reload_ext autoreload
%autoreload 2

In [8]:
import models

# Model

In [225]:
rnn = models.rnn.RNN()

In [226]:
x = torch.randn((2, 5))

In [227]:
rnn.reset()

In [231]:
print(len(rnn.context))
rnn(x)

4


tensor([[-0.0923, -0.0272, -0.1879,  0.1355],
        [-0.2255,  0.0597, -0.3723,  0.2359]], grad_fn=<AddmmBackward>)

In [232]:
rnn.context

deque([tensor([[0., 0., 0., 0., 0.],
               [0., 0., 0., 0., 0.]]),
       tensor([[0.0000, 0.2123, 0.3658, 0.0000, 0.0558],
               [0.1162, 0.0000, 0.0000, 0.0000, 0.0000]], grad_fn=<MulBackward0>),
       tensor([[0.0000, 0.1445, 0.5215, 0.0000, 0.0000],
               [0.1361, 0.0000, 0.0000, 0.0000, 0.0000]], grad_fn=<MulBackward0>),
       tensor([[0.0000, 0.0000, 0.5565, 0.0000, 0.0000],
               [0.1395, 0.0000, 0.0000, 0.0000, 0.0000]], grad_fn=<MulBackward0>),
       tensor([[0.0000, 0.0000, 0.5175, 0.0000, 0.0105],
               [0.0652, 0.0000, 0.0000, 0.0000, 0.0000]], grad_fn=<MulBackward0>)])

In [243]:
rnn.first_context.data

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [251]:
rnn.zero_grad()

In [252]:
optimiser = torch.optim.Adam(rnn.parameters())

In [253]:
optimiser.step()

In [254]:
rnn.action_layer.bias.grad

tensor([0., 0., 0., 0.])

In [255]:
rnn.zero_grad()
x = torch.randn((2, 5))
x = rnn(x)
loss = x.pow(2).mean()
loss.backward()
optimiser.step()

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [242]:
rnn.first_context

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)