In [1]:
import gym
import time

In [63]:
import numpy as np

In [2]:
environment = gym.make('Breakout-ram-v0')

# Getting the byte for the ball and bar

## Bar

In [539]:
state = environment.reset()

In [540]:
observations = []

In [562]:
environment.render()
observation, reward, done, info = environment.step(3)
observations.append(observation)
print(reward, info)

0.0 {'ale.lives': 5}


In [563]:
obs = np.array(observations)

In [564]:
obs.std(axis=0)

array([  0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.  

In [569]:
bar_states = ['.'.join([str(r) for r in row[bar_features]]) for row in observations]

In [570]:
np.unique(bar_states)

array(['0.6.191.4.13.64.0.255', '106.3.139.5.0.3.225.5',
       '114.6.109.4.13.44.0.255', '12.6.191.4.13.66.0.255',
       '122.6.123.2.0.6.222.4', '138.6.85.4.13.40.0.255',
       '140.3.106.6.2.9.219.4', '154.6.69.4.13.37.0.255',
       '164.5.82.6.4.13.215.3', '172.2.56.2.12.34.194.0',
       '180.2.66.2.5.16.212.3', '184.3.55.2.9.27.201.1',
       '184.3.55.4.7.21.207.2', '184.5.55.3.11.31.197.0',
       '184.5.55.8.7.19.209.2', '184.6.55.6.8.24.204.1',
       '24.6.191.4.13.60.0.255', '40.6.183.4.13.57.0.255',
       '64.6.161.4.13.53.0.255', '74.6.149.4.13.51.0.255',
       '86.6.137.4.13.49.0.255', '98.6.126.4.13.47.0.255'], dtype='<U23')

In [565]:
bar_features = np.arange(128)[obs.std(axis=0) > 0]
bar_features

array([ 70,  71,  72,  74,  75,  90,  94, 119])

## Ball

In [642]:
state = environment.reset()

In [643]:
observations = []

In [703]:
environment.render()
observation, reward, done, info = environment.step(1)
observations.append(observation)
print(reward, info)

0.0 {'ale.lives': 4}


In [704]:
obs = np.array(observations)

In [705]:
obs.std(axis=0)

array([  0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.49553562,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.  

In [706]:
ball_states = ['.'.join([str(r) for r in row[ball_features]]) for row in observations]

In [708]:
len(np.unique(ball_states))

60

In [533]:
ball_features = np.arange(128)[obs.std(axis=0) > 0]
ball_features

array([ 57,  71,  74,  75,  86,  90,  94,  95,  99, 101, 103, 105, 119])

In [534]:
environment.close()

In [535]:
features = np.unique(list(bar_features) + list(ball_features))

In [538]:
features

array([ 57,  70,  71,  72,  74,  75,  86,  90,  94,  95,  99, 101, 103,
       105, 119])